server:
  port: 8087

spring:
  application:
    name: customer

  datasource:
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5433/customer
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka
      fetch-registry: true
      register-with-eureka: true


