server:
  port: 8083

spring:
  application:
    name: fraud

  datasource:
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5433/fraud
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
